import type { Pages, PageResponse } from '../types';
import type { NextPage } from 'next';
import Head from 'next/head';
import About from '../components/About';
import Contact from '../components/Contact';
import Hero from '../components/Hero';
import Menu from '../components/Menu';
import Partners from '../components/Partners';
import Products from '../components/Products';

function getContent
  (pages: PageResponse[], pageTitle: string): string {
  const content = pages.filter(
    page => new RegExp(pageTitle, 'i').test(page.title.rendered)
  );
  return content.length ?
    (content.shift() as PageResponse).content.rendered : '';
}

const Home: NextPage<Pages> = ({ pages }) => {
  const content = getContent.bind(null, pages);

  return (
    <>
      <Head>
        <title>ALP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Menu />
      </header>
      <main>
        <Hero />
        <section id="proposta">
          <About />
        </section>
        <section id="produtos">
          <Products />
        </section>
        <section id="quem-somos">
          <Partners content={content('quem somos')} />
        </section>
        <section id="contato">
          <Contact />
        </section>
      </main>
    </>
  )
};

export async function getStaticProps() {
  const getApiRoute: (fields: string | null) => string = (fields) => {
    const isProd: boolean = /prod/i.test(process.env.NODE_ENV);
    const host: string = isProd ? '' : 'localhost:8000';
    const pageRoute: string = 'wp-json/wp/v2/pages';
    const _fields = fields ? `?_fields=${fields}` : '';

    return `http${isProd ? 's' : ''}://${host}/${pageRoute}${_fields}`;
  };

  const pages = await fetch(getApiRoute('title, content'))
    .then((response: void | Response) => {
      if (!response || !response.ok) {
        throw new Error(`Error: ${(response as Response).status}`);
      }
      return response.json();
    });

  return {
    props: {
      pages
    }
  }
}

export default Home;